@extends('errors.layout')
@section('title', 'Terlalu Banyak Permintaan')
@section('code', '429')
@section('icon', '🛑')
@section('description', 'Anda mengirim terlalu banyak permintaan dalam waktu singkat. Silakan tunggu beberapa saat sebelum mencoba lagi.')
